### ISSUE TITLE
extension not working

### ISSUE THREAD

**Issue by bisnowhere** [SuhasDissa/NotQuiteNitro#13]
hi! i'm the person from the review in the firefox page. Thank you for reaching out to me! 
So, i downloaded the extension and checked permissions. It seems to be on(the emotes are not faded out like they are without the extension and it says it's active in the add-ons page), but nothing happens when i click the emotes in the tab or type them out. Am i doing it wrong? Are there any extra settings i need to do?

**Comment by SuhasDissa** [comment]
This extension will copy the image URL of any Discord emote to your clipboard when you click on it. Just paste the URL into the chat area and send it, and Discord will automatically convert it to the emote.

Unfortunately, due to limitations in the Discord website, this extension can't automatically paste the emote link into the chat area for you. But don't worry, it's still super easy to use. Just copy and paste the URL, and you're good to go!

**Comment by bisnowhere** [comment]
OHHHH i see! Yeah, it works perfectly! Thanks for the clarification LMAO
